feed/urls.py
from django.conf.urls import url
from feed.views.feed_view import FeedView

app_name = 'feed'
urlpatterns = [
    url(r'^$', FeedView.as_view(), name='index'),
]

report/urls.py
from django.conf.urls import url

from report.views.report_params_view import ReportParamsView
from report.views.report_view import ReportView

app_name = 'report'
urlpatterns = [
    url(r'new$', ReportParamsView.as_view(), name='new'),
    url(r'view/(?P<start>\d+-\d+-\d+)/(?P<end>\d+-\d+-\d+)$', ReportView.as_view(), name='view')
]

selfie/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^post/', include('posts.urls')),
    url(r'^feed/', include('feed.urls')),
    url(r'^registration/', include('registration.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^vote/', include('vote.urls')),
    url(r'^claim/', include('claim.urls')),
    url(r'^users/', include('user_management.urls')),
    url(r'^profile/', include('user_profile.urls')),
    url(r'^plan/', include('plan.urls')),
    url(r'^payment/', include('payment.urls')),
    url(r'^subscriptions/', include('subscription_management.urls')),
    url(r'^report/', include('report.urls')),
    url(r'^$', include('home.urls')),
    url(r'^user_list/', include('user.urls')),
    url(r'^logout/', include('logout.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

report/models/report.py
from django.db import models
from posts.models.post import Post
from user.models import User

class Report(models.Model):
    user = models.ForeignKey(User)
    post = models.ForeignKey(Post)
    reason = models.CharField(max_length=255)

report/forms/report_form.py
from django import forms

class ReportForm(forms.Form):
    reason = forms.CharField(
        label='Введите причину жалобы',
        max_length=255,
        widget=forms.Textarea
    )

report/forms/report_params_form.py
from django import forms
import html5.forms.widgets as html5_widgets

class ReportParamsForm(forms.Form):
    start = forms.DateField(label="Дата начала", widget=html5_widgets.DateInput)
    end = forms.DateField(label="Дата окончания", widget=html5_widgets.DateInput)

report/views/report_params_view.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views.generic import View
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.mixins import LoginRequiredMixin

from report.forms.report_params_form import ReportParamsForm

class ReportParamsView(UserPassesTestMixin, LoginRequiredMixin, View):
    login_url = '/login/'
    form_class = ReportParamsForm
    template_name = 'report/report_params_page.html'

    def get(self, request):
        form = self.form_class()

        return render(request, self.template_name, {'form': form})

    def post(self, request):
        print(request.POST)
        return HttpResponseRedirect(reverse('report:view',
                                    kwargs={'start': request.POST['start'], 'end': request.POST['end']}))

    def test_func(self):
        return self.request.user.role == 4

report/views/report_view.py
from datetime import datetime
from django.shortcuts import render
from django.contrib import messages
from django.views.generic import View
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from payment.adapters.payment_adapter import PaymentAdapter
from printer.adapters.printer_adapter import PrinterAdapter
from report.report import Report

class ReportView(UserPassesTestMixin, LoginRequiredMixin, View):
    login_url = '/login/'
    template_name = 'report/report_page.html'

    def get(self, request, start, end):
        start = datetime.strptime(start, '%Y-%m-%d')
        end = datetime.strptime(end, '%Y-%m-%d')
        transactions = PaymentAdapter.get_report_data(start, end)

        return render(request, self.template_name,
                      {'transactions': transactions, 'start': start, 'end': end})

    def post(self, request, start, end):
        return self.view_report(request, start, end)

    def test_func(self):
        return self.request.user.role == 4

    def view_report(self, request, start, end):
        start = datetime.strptime(start, '%Y-%m-%d')
        end = datetime.strptime(end, '%Y-%m-%d')
        transactions = PaymentAdapter.get_report_data(start, end)
        report = Report()
        PrinterAdapter.print_report(report)
        messages.add_message(request, messages.INFO, 'Печать отчёта запланирована.')

        return render(request, self.template_name,
                      {'transactions': transactions, 'start': start, 'end': end})

    def view_vip_user_report(self, request, start, end):
        pass

report/templates/report/new_report.html
{% extends "base.html" %}

{% block content %}

<form action="{% url "report:new" post_id=post_id %}" method="post">
    {% csrf_token %}
    <p>{{ form.non_field_errors }}</p>

    <p>{{ form.reason.label_tag }} {{ form.reason.help_text }}</p>

    <p>
        {{ form.reason.errors }}
        {{ form.reason }}
    </p>

    <p><input type="submit" value="Отправить жалобу"/></p>
</form>

{% endblock %}

report/templates/report/report_page.html
{% extends "base.html" %}

{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<h1>Просмотр финансового отчёта с {{start}} по {{end}}</h1>

{% if transactions %}
  <table border="1">
  <tr>
    <th>Покупатель</th>
    <th>Сумма</th>
    <th>Счёт</th>
    <th>Дата</th>
  </tr>
    {% for transaction in transactions %}
      <tr>
        <td>{{transaction.subscription_set.all.first.customer.username}}</td>
        <td>{{transaction.amount}}</td>
        <td>{{transaction.bill}}</td>
        <td>{{transaction.date}}</td>
      </tr>
    {% endfor %}
  </table>
{% else %}
  <p>Нет записей.</p>
{% endif %}
<form action="" method="post">
  {% csrf_token %}
  <p><input type="submit" value="Распечатать отчёт"/></p>
</form>
{% endblock %}

report/templates/report/report_params_page.html
{% extends "base.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <p>{{ form.non_field_errors }}</p>

    <p>{{ form.start.label_tag }} {{ form.start.help_text }}</p>
    <p>
        {{ form.start }}
    </p>

    <p>{{ form.end.label_tag }} {{ form.end.help_text }}</p>
    <p>
        {{ form.end }}
    </p>

    <p><input type="submit" value="Сгенерировать отчёт"/></p>
</form>

{% endblock %}